In [1]:
# pip install pooled-ppi @ git+https://github.com/jurgjn/pooled-ppi@develop
import pooled_ppi.yeast_pools as yp

yeast_pools.py:22 Using data from: /cluster/work/beltrao/jjaenes/25.12_pooled-ppi-yeast/data-26.07
/cluster/work/beltrao/jjaenes/25.12_pooled-ppi-yeast/data-26.07/resources/.cached_path

In [2]:
# o13297 homodimer is in paired input, and one pooled input (each input has 5 models)
# filters argument (to select pairs) is passed on to pd.read_parquet
# foldcomp database identifiers are now {input_name}_{sample}_{chain_id}
# - input_name is either chain uniprot identifiers (for pairs) or hash of the chain identifiers (for pools)
# - sample is from AlphaFold3 (diffusion model sample)
# - chain_id is the original chain identifier in the AlphaFold3 mmcif; foldcomp does not support multimer entries so we're storing individual chains
af3_id = 'o13297'
yp.get_models(filters=[('af3_id1', '==', af3_id), ('af3_id2', '==', af3_id)])

,af3_id1,af3_id2,chain_id1,chain_id2,input_name,input_type,sample,ranking_score,chain_pair_iptm,chain_pair_pae_min,db_id1,db_id2
0,o13297,o13297,A,B,o13297_o13297,pair,0,0.782783,0.55,1.49,o13297_o13297_0_A,o13297_o13297_0_B
1,o13297,o13297,A,B,o13297_o13297,pair,1,0.773146,0.54,1.56,o13297_o13297_1_A,o13297_o13297_1_B
2,o13297,o13297,A,B,o13297_o13297,pair,2,0.741119,0.55,1.54,o13297_o13297_2_A,o13297_o13297_2_B
3,o13297,o13297,A,B,o13297_o13297,pair,3,0.783007,0.55,1.32,o13297_o13297_3_A,o13297_o13297_3_B
4,o13297,o13297,A,B,o13297_o13297,pair,4,0.752487,0.55,1.52,o13297_o13297_4_A,o13297_o13297_4_B
5,o13297,o13297,A,B,fc40a600fabb4ea278771889c9e11ea3e2cda50a,pool,0,0.338259,0.41,5.62,fc40a600fabb4ea278771889c9e11ea3e2cda50a_0_A,fc40a600fabb4ea278771889c9e11ea3e2cda50a_0_B
6,o13297,o13297,A,B,fc40a600fabb4ea278771889c9e11ea3e2cda50a,pool,1,0.356276,0.40,5.79,fc40a600fabb4ea278771889c9e11ea3e2cda50a_1_A,fc40a600fabb4ea278771889c9e11ea3e2cda50a_1_B
7,o13297,o13297,A,B,fc40a600fabb4ea278771889c9e11ea3e2cda50a,pool,2,0.358208,0.40,6.27,fc40a600fabb4ea278771889c9e11ea3e2cda50a_2_A,fc40a600fabb4ea278771889c9e11ea3e2cda50a_2_B
8,o13297,o13297,A,B,fc40a600fabb4ea278771889c9e11ea3e2cda50a,pool,3,0.344496,0.39,6.45,fc40a600fabb4ea278771889c9e11ea3e2cda50a_3_A,fc40a600fabb4ea278771889c9e11ea3e2cda50a_3_B
9,o13297,o13297,A,B,fc40a600fabb4ea278771889c9e11ea3e2cda50a,pool,4,0.343412,0.39,6.52,fc40a600fabb4ea278771889c9e11ea3e2cda50a_4_A,fc40a600fabb4ea278771889c9e11ea3e2cda50a_4_B

In [3]:
# extract first model (sample==0) from pair and pool
models = yp.get_models(filters=[('af3_id1', '==', af3_id), ('af3_id2', '==', af3_id), ('sample', '==', 0)])
models

,af3_id1,af3_id2,chain_id1,chain_id2,input_name,input_type,sample,ranking_score,chain_pair_iptm,chain_pair_pae_min,db_id1,db_id2
0,o13297,o13297,A,B,o13297_o13297,pair,0,0.782783,0.55,1.49,o13297_o13297_0_A,o13297_o13297_0_B
1,o13297,o13297,A,B,fc40a600fabb4ea278771889c9e11ea3e2cda50a,pool,0,0.338259,0.41,5.62,fc40a600fabb4ea278771889c9e11ea3e2cda50a_0_A,fc40a600fabb4ea278771889c9e11ea3e2cda50a_0_B

In [4]:
# use db_id1, db_id2 to save the individual heterodimers as PDB files
for i, row in models.iterrows():
    path = f'{row.af3_id1}_{row.af3_id2}_{row.input_type}_{row["sample"]}.pdb'
    yp.save_predictions_db([row.db_id1, row.db_id2], path)
    print(path, 'written')

o13297_o13297_pair_0.pdb written
o13297_o13297_pool_0.pdb written

In [5]:
# Current directory has PDBs
!ls -l *.pdb

-rw-r--r-- 1 jjaenes biol-imsb-beltrao 705033 Jul 14 16:04 o13297_o13297_pair_0.pdb
-rw-r--r-- 1 jjaenes biol-imsb-beltrao 705033 Jul 14 16:04 o13297_o13297_pool_0.pdb